version: "3.8"

services:

  transport-commands:
    build:
      context: ../transport_service_commands/
      dockerfile: Dockerfile
    container_name: 'transport-commands'
    restart: always
    environment:
      - POSTGRES_USR=admin
      - POSTGRES_PWD=admin
      - POSTGRES_HOST=postgres-db
      - POSTGRES_DATABASE=transport_commands_db_175132
      - POSTGRES_PORT=5432
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USR=guest
      - RABBIT_PWD=guest

  transport-queries:
    build:
      context: ../transport_service_queries/
      dockerfile: Dockerfile
    container_name: 'transport-queries'
    restart: always
    environment:
      - MONGO_USER=admin
      - MONGO_PWD=admin
      - MONGO_HOST=mongo-db
      - MONGO_DATABASE=175132_transport_queries_db
      - MONGO_PORT=27017
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USR=guest
      - RABBIT_PWD=guest

  api-gateway:
    build:
      context: ../api_gateway/
      dockerfile: Dockerfile
    container_name: 'api-gateway'
    restart: always
    ports:
      - 17515:8080
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USR=guest
      - RABBIT_PWD=guest
      - TIMEOUT=2

  userservice:
    container_name: 'userservice'
    build:
      context: ../userservice/
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres-db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=userservice_db_175132
      - AMQP_HOST=rabbitmq

  frontend:
    container_name: 'frontend'
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    ports:
      - 80:80

  payment:
    build:
      context: ../payment_service
      dockerfile: Dockerfile
    container_name: 'payment'
    environment:
      - AMQP_URL=rabbitmq
      - REJECTION_PROBABILITY=10

  accommodation_service_commands:
    container_name: accommodation_service_commands
    build:
      context: ../accommodation_service_commands
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=accommodation_service_commands_db_175132
      - POSTGRES_USER=admin
      - POSTGRES_PWD=admin
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USR=guest
      - RABBIT_PWD=guest

  accommodation_service_queries:
    build:
      context: ../accommodation_service_queries
      dockerfile: Dockerfile
    container_name: accommodation_service_queries
    environment:
      - MONGO_USER=admin
      - MONGO_USER_PWD=admin
      - MONGO_HOST=mongo-db
      - DATABASE_NAME=175132_accommodation_service_queries_db
      - MONGO_PORT=27017
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USR=guest
      - RABBIT_PWD=guest

  trip_service:
    container_name: trip_service
    build:
      context: ../trip_service
      dockerfile: Dockerfile
    environment:
      - MONGO_USER=admin
      - MONGO_USER_PWD=admin
      - MONGO_HOST=mongo-db
      - DATABASE_NAME=175132_trip_service_db
      - MONGO_PORT=27017
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USR=guest
      - RABBIT_PWD=guest

  tour_operator:
    container_name: tour_operator
    build:
      context: ../tour_operator
      dockerfile: Dockerfile
    environment:
      - AMQP_URL=rabbitmq
      - REJECTION_PROBABILITY=10
      